### ISSUE TITLE
biblatex + REVTeX

### ISSUE THREAD

**Issue by adoa** [josephwright/biblatex-phys#12]
`biblatex-phys` is designed to mimic the behavior of REVTeX. I have a question regarding this very simple fact. REVTeX, as far as I have understood, uses `natbib` internally. But I cannot load `biblatex` is `natbib` is loaded. However, APS and AIP demand the use of the REVTeX class.

Can I use `biblatex` + `biblatex-phys` + biber in combination with REVTeX for manuscripts? Is there a "fork" of REVTeX that does not use `natbib`? How else am I supposed to use `biblatex-phys`?

**Comment by josephwright** [comment]
The `biblatex-phys` bundle exists to allow people requiring physics bibliography styles to do so in combination with `biblatex`, for example in reports, theses, _etc._

For submission to journal you always need to check exactly what they mandate/support. In the case of the APS and AIP they require use of REVTeX and so that's what you should use: load _only_ such additional packages as are _required_ to write your document. In particular, you _have_ to use the `natbib` interface for referencing and the official styles which go with that (_i.e._ you can't  choose a different `.bst` file from those that come with REVTeX, much less a different bibliography approach entirely).

**Comment by yuttai** [comment]
Even if I want to submit to APS, can I follow the following workaround to set aside `natbib` and use `biblatex`? Since we still loads `natbib,` but just ignore it.
https://tex.stackexchange.com/questions/37076/is-it-possible-to-load-biblatex-with-a-class-that-has-already-loaded-natbib/37077#37077

Besides, since APS requires journal abbreviations, is it possible to display `shortjournal` field instead of `journaltitle` field when `shortjournal` field is available? Thanks.

**Comment by josephwright** [comment]
I really can't recommend using `biblatex` to submit to a journal which doesn't support it. For titles, I would expect you to simply abbreviate in your database: certainly I never store full journal titles as my subject area (chemistry) always cites using abbreviations.

**Comment by yuttai** [comment]
Thanks for your suggestion! 
After I found your method in stackexchange cannot work in LyX, I rolled back to bibTeX... (sigh)
And I will use abbreviations in the journal in .bib file : )
